In [1]:
import pandas as pd 

data = {
    "note_id": [1, 2, 3, 4, 5],
    "claim": [
        "Jupyter helps organize code",
        "GitHub stores projects",
        "Python automates checking",
        "",
        "Pandas creates data tables"
    ],
    "source_file": [
        "paper.pdf",
        "paper.pdf",
        "",
        "paper.pdf",
        "paper.pdf"
    ],
    "page_number": [
        2,
        4,
        6,
        "",
        -1
    ],
    "evidence_snippet": [
        "Example evidence",
        "Example evidence",
        "Example evidence",
        "",
        "Example evidence"
    ],
    "status": [
        "",
        "",
        "",
        "",
        ""
    ]
}

df = pd.DataFrame(data)

df
df.to_csv("sample_notes.csv", index=False)

print("CSV successfully created!")

CSV successfully created!

In [2]:
import pandas as pd

df = pd.read_csv("sample_notes.csv")

df
def check_row(row):

    if row["claim"] == "":
        return "ERROR"

    if row["source_file"] == "":
        return "ERROR"

    if pd.isna(row["page_number"]):
        return "ERROR"

    return "PASS"
   
    df["status"] = df.apply(check_row, axis=1)

df

def check_row(row):

    if row["claim"] == "":
        return "ERROR"

    if row["source_file"] == "":
        return "ERROR"

    if pd.isna(row["page_number"]):
        return "ERROR"

    if row["evidence_snippet"] == "":
        return "WARNING"

    return "PASS"


df.to_csv("checked_notes.csv", index=False)

print("Checker finished!")

Checker finished!

In [3]:
import os

print(os.getcwd())

/Users/briankinyua/project_practice

In [4]:
import os

print(os.getcwd())

print(os.listdir())

from pathlib import Path

PDF_FILE = Path("ten_simple_rules.pdf")

import pypdf

reader = pypdf.PdfReader(str(PDF_FILE))

print(len(reader.pages))

/Users/briankinyua/project_practice
['Wk4_checker.ipynb', 'explanation.txt', 'checked_notes.csv', 'ten_simple_rules.pdf', 'sample_notes.csv', '.ipynb_checkpoints', 'src']
8

In [5]:
#extracting the texts from every page
pages = []

for page_number, page in enumerate(reader.pages, start=1):

    text = page.extract_text()

    pages.append({
        "page_number": page_number,
        "page_text": text
    })

import pandas as pd

pages_df = pd.DataFrame(pages)

pages_df.head()

#combining the pages together
paper_text = ""

for row in pages:
    paper_text += f"\n\nPAGE {row['page_number']}\n"

    paper_text += row["page_text"]

print(len(paper_text))

29078

In [6]:
from pathlib import Path
import pypdf
import pandas as pd

PDF_FILE = Path("ten_simple_rules.pdf")

reader = pypdf.PdfReader(str(PDF_FILE))

pages = []

for page_number, page in enumerate(reader.pages, start=1):
    pages.append({
        "page_number": page_number,
        "page_text": (page.extract_text() or "").strip()
    })

print(f"Extracted{len(pages)} pages.")
pages_df = pd.DataFrame(pages)

display(pages_df.head())


from pathlib import Path
import pypdf
import pandas as pd

PDF_FILE = Path("ten_simple_rules.pdf")

reader = pypdf.PdfReader(str(PDF_FILE))

pages = []

for page_number, page in enumerate(reader.pages, start=1):
    pages.append({
        "page_number": page_number,
        "page_text": (page.extract_text() or "").strip()
    })

pages_df = pd.DataFrame(pages)

display(pages_df.head())

Extracted8 pages.

   page_number                                          page_text
0            1  EDITOR IAL\nTen simple rules for writing and s...
1            2  environments for replicating, exploring, and e...
2            3  you did but why you did it, how the steps are ...
3            4  Avoid long cells (we suggest that anything ove...
4            5  However, be aware that Jupyter Notebooks store...

   page_number                                          page_text
0            1  EDITOR IAL\nTen simple rules for writing and s...
1            2  environments for replicating, exploring, and e...
2            3  you did but why you did it, how the steps are ...
3            4  Avoid long cells (we suggest that anything ove...
4            5  However, be aware that Jupyter Notebooks store...

In [7]:

records = [
    {
        "record_id": "BRIAN-S2N-001",
        "source_filename": "ten_simple_rules.pdf",
        "source_page_number": 2,
        "claim_summary": "Computational notebooks require careful use because interactive editing can introduce errors that make research difficult to reproduce.",
        "exact_evidence_snippet": "Interactively running and editing code in notebooks can delete key steps or introduce “hidden state” that confounds analyses and confuses readers.",
        "status": "Supported",
        "reviewer_decision": "Pending",
        "reviewer_comment": ""
    },

    {
        "record_id": "BRIAN-S2N-002",
        "source_filename": "ten_simple_rules.pdf",
        "source_page_number": 2,
        "claim_summary": "Researchers should document their software environment and share dependencies so others can successfully rerun their analyses.",
        "exact_evidence_snippet": "Analyses documented in notebooks cannot be easily rerun if users do not first freeze their dependencies, share their data, and adequately describe their computing environment.",
        "status": "Supported",
        "reviewer_decision": "Pending",
        "reviewer_comment": ""
    },

    {
        "record_id": "BRIAN-S2N-003",
        "source_filename": "ten_simple_rules.pdf",
        "source_page_number": 2,
        "claim_summary": "The authors created a set of practical rules to help researchers use and share Jupyter Notebooks more effectively.",
        "exact_evidence_snippet": "Given these opportunities and challenges, we have compiled a set of rules, tips, tools, and example notebooks to help guide Jupyter Notebook authors.",
        "status": "Supported",
        "reviewer_decision": "Pending",
        "reviewer_comment": ""
    }
]

In [8]:
import pandas as pd

notes_df = pd.DataFrame(records)

notes_df

,record_id,source_filename,source_page_number,claim_summary,exact_evidence_snippet,status,reviewer_decision,reviewer_comment
0,BRIAN-S2N-001,ten_simple_rules.pdf,2,Computational notebooks require careful use be...,Interactively running and editing code in note...,Supported,Pending,
1,BRIAN-S2N-002,ten_simple_rules.pdf,2,Researchers should document their software env...,Analyses documented in notebooks cannot be eas...,Supported,Pending,
2,BRIAN-S2N-003,ten_simple_rules.pdf,2,The authors created a set of practical rules t...,"Given these opportunities and challenges, we h...",Supported,Pending,

In [9]:
print(type(pages))

<class 'list'>

In [10]:

#created a page lookup
page_text_lookup = {
    row["page_number"]: row["page_text"]
    for row in pages
}

print("Page lookup created!")

Page lookup created!

In [11]:
#create the checker 
def validate_note(row):

    page_number = row["source_page_number"]
    evidence = str(row["exact_evidence_snippet"]).strip()

    if pd.isna(page_number):
        return "Needs Review", "Missing page number."

    try:
        page_number = int(page_number)
    except:
        return "Needs Review", "Invalid page number."

    if page_number not in page_text_lookup:
        return "Needs Review", "Page does not exist."

    page_text = page_text_lookup[page_number]

    if evidence not in page_text:
        return "Needs Review", "Evidence not found on page."

    return "Supported", "Evidence verified."

In [12]:
#Define the checker
def validate_note(row):
    page_number = row["source_page_number"]
    evidence = str(row["exact_evidence_snippet"]).strip()

    if pd.isna(page_number):
        return "Needs Review", "Missing page number."

    try:
        page_number = int(page_number)
    except (TypeError, ValueError):
        return "Needs Review", "Invalid page number."

    if page_number not in page_text_lookup:
        return "Needs Review", "Page does not exist."

    page_text = page_text_lookup[page_number]

    if evidence not in page_text:
        return "Needs Review", "Evidence not found on page."

    return "Supported", "Evidence verified."

In [13]:
#apply the checker 
results = notes_df.apply(validate_note, axis=1)

notes_df["status"] = [r[0] for r in results]

notes_df["automatic_check_comment"] = [r[1] for r in results]

notes_df

,record_id,source_filename,source_page_number,claim_summary,exact_evidence_snippet,status,reviewer_decision,reviewer_comment,automatic_check_comment
0,BRIAN-S2N-001,ten_simple_rules.pdf,2,Computational notebooks require careful use be...,Interactively running and editing code in note...,Needs Review,Pending,,Evidence not found on page.
1,BRIAN-S2N-002,ten_simple_rules.pdf,2,Researchers should document their software env...,Analyses documented in notebooks cannot be eas...,Needs Review,Pending,,Evidence not found on page.
2,BRIAN-S2N-003,ten_simple_rules.pdf,2,The authors created a set of practical rules t...,"Given these opportunities and challenges, we h...",Needs Review,Pending,,Evidence not found on page.